name: deploy-book

on:
  push:
    branches:
      - main   # change to "master" if that’s your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install --pre "jupyter-book==2.*" ghp-import

      - name: Build the book
        run: jupyter-book build --all

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ghp-import -n -p -f _build/site -r "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
